# pyproject.toml

[tool.black]
line-length = 120
target-version = ['py39']

[tool.isort]
profile = "black"
skip = ["__init__.py"]

[tool.pylint]
disable = [
    "unused-argument",
    "dangerous-default-value",
    "missing-docstring",
    "invalid-name",
    "too-few-public-methods",
    "too-many-arguments",
    "too-many-locals",
    "too-many-branches",
    "too-many-statements",
    "too-many-instance-attributes",
    "too-many-public-methods",
    "too-many-lines",
    "too-many-ancestors",
    "too-many-function-args",
    "too-many-function-args",
    "too-many-return-statements",
    "too-many-boolean-expressions",
    "too-many-arguments",
    "too-many-locals",
    "too-many-branches",
    "too-many-statements",
    "too-many-instance-attributes",
    "too-many-public-methods",
    "too-many-lines",
    "too-many-ancestors",
    "too-many-function-args",
    "too-many-function-args",
    "too-many-return-statements",
    "too-many-boolean-expressions",
    "too-many-arguments",
    "too-many-locals",
    "too-many-branches",
    "too-many-statements",
    "too-many-instance-attributes",
    "too-many-public-methods",
    "too-many-lines",
    "too-many-ancestors",
    "too-many-function-args",
    "too-many-function-args",
    "too-many-return-statements",
    "too-many-boolean-expressions",
    "too-many-arguments",
    "too-many-locals",
    "too-many-branches",
    "too-many-statements",
    "too-many-instance-attributes",
    "too-many-public-methods",
    "too-many-lines",
    "too-many-ancestors",
    "too-many-function-args",
    "too-many-function-args",
    "too-many-return-statements",
    "too-many-boolean-expressions",
    "too-many-arguments",
    "too-many-locals",
    "too-many-branches",
    "too-many-statements",
    "too-many-instance-attributes",
    "too-many-public-methods",
    "too-many-lines",
    "too-many-ancestors",
    "too-many-function-args",
    "too-many-function-args",
    "too-many-return-statements",
    "too-many-boolean-expressions",
    "too-many-arguments",
    "too-many-locals",
    "too-many-branches",
    "too-many-statements",
    "too-many-instance-attributes",
    "too-many-public-methods",
    "too-many-lines",
    "too-many-ancestors",
    "too-many-function-args",
    "too-many-function-args",
    "too-many-return-statements",
    "too-many-boolean-expressions",
    "invalid-str-returned",
    "ungrouped-imports"
]
max-line-length = 120
ignore = [
    "tests/*",
    "docs/*",
    "build/*",
    "dist/*",
    "venv/*",
    "env/*",
    "site/*",
    "lib/*",
    "bin/*",
    "include/*",
    "share/*",
    "var/*",
    "tmp/*",
    "usr/*",
    "opt/*",
    "srv/*",
    "root/*",
    "run/*",
    "mnt/*",
    "media/*",
    "lost+found/*",
    "home/*",
    "etc/*",
    "dev/*",
    "boot/*",
    "sys",
]
