---
- name: Install Nginx
  become: true
  apt:
    pkg: 
    - nginx
    - python3-certbot-nginx
    - certbot
    state: present

- name: Ensure Nginx is running
  become: true
  service:
    name: nginx
    state: started
    enabled: true

- name: Obtain SSL certificate
  become: true
  command: certbot --nginx -d {{ server_name }} --non-interactive --agree-tos --email {{ nginx_email }}
  when: nginx_ssl_enabled | bool

- name: Configure Nginx
  become: true
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/sites-available/default
  notify: Restart Nginx

- name: Reload Nginx to apply changes
  become: true
  service:
    name: nginx
    state: reloaded